services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: njotify
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  backend:
    build:
      context: ./Backend
    container_name: backend
    command: go run server.go
    volumes:
      - ./Backend:/app
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: password123
      DB_NAME: njotify
    depends_on:
      - redis
      - postgres

  frontend:
    build:
      context: ./NJotify
    container_name: frontend
    volumes:
      - ./NJotify:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
